version: '3.9'
name: accounting-system

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: accounting
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

  backend-php:
    build:
      context: ./backend
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=accounting
      - DB_USERNAME=app
      - DB_PASSWORD=app

  backend-nginx:
    image: nginx:1.27-alpine
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
      - ./backend/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend-php

  frontend:
    build:
      context: ./frontend-web
      dockerfile: docker/dev.Dockerfile
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
      # Base URL used by the browser to reach backend via host mapping
      - NEXT_PUBLIC_API_BASE=http://localhost:8080/api/v1
      - PORT=3000
      - HOST=0.0.0.0
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-web:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend-nginx

volumes:
  db_data:
